apiVersion: v1
kind: PersistentVolume
metadata:
  name: jasminegraph-local-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/jasminegraph"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasminegraph-local-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi