apiVersion: v1
kind: Service
metadata:
  name: jasminegraph-worker<worker-id>-service
  labels:
    application: jasminegraph
    service: jasminegraph-worker
    workerId: <worker-id>
spec:
  ports:
    - port: 7780
      name: 'server-port'
    - port: 7781
      name: 'server-data-port'
  selector:
    type: worker
    workerId: <worker-id>
    service: jasminegraph
  type: ClusterIP