name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Customize the build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
        fetch-depth: 0
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    - uses: jupyterhub/action-k3s-helm@v3
      with:
        docker-enabled: true

    - name: Run unit test
      run: |
        docker pull ishad1999/jasminegraph
        kubectl apply -f ./.github/workflows/resources/prerequisite-pod.yaml
        sleep 30
        kubectl get pods
        kubectl exec jasminegraph-prerequisite -- bash -c "pip install gcovr && cd /home/ubuntu/software/jasminegraph && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG .. && LD_LIBRARY_PATH=/usr/local/lib make -j4 && LD_LIBRARY_PATH=/usr/local/lib make -j2 coverage"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Docker Build
      # Build JasmineGraph docker image
      run: docker build -t jasminegraph .

    - name: Run Integration Tests
      run: |
        chmod +x test-docker.sh
        ./test-docker.sh
