name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Customize the build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
        fetch-depth: 0
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    - uses: jupyterhub/action-k3s-helm@v3
      with:
        docker-enabled: true

    - name: Docker Build
      # Build JasmineGraph docker image
      run: docker build -t jasminegraph .

    - name: Build unit test
      run: docker build -f ./tests/unit/Dockerfile -t jasminegraph:unit .

    - name: Run unit test
      run: |
        mkdir coverage
        kubectl apply -f ./.github/workflows/resources/unit-test-conf.yaml
        sleep 30
        kubectl logs -f jasminegraph-unit-test-pod

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage/coverage.xml
        fail_ci_if_error: true


    - name: Run Integration Tests
      run: |
        chmod +x test-docker.sh
        ./test-docker.sh
