name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip unit tests')}}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      - uses: jupyterhub/action-k3s-helm@v4
        with:
          docker-enabled: true

      - name: Grant permissions for default user
        run: kubectl apply -f ./k8s/rbac.yaml

      - name: Build unit test
        run: docker build -f ./tests/unit/Dockerfile -t jasminegraph:unit .

      - name: Run unit test
        run: |
          mkdir coverage
          kubectl apply -f ./.github/workflows/resources/unit-test-conf.yaml
          sleep 30
          kubectl logs -f jasminegraph-unit-test-pod

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage/coverage.xml
          fail_ci_if_error: true

  docker-integration-tests:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip docker integration')}}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.head_ref}}
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

    - name: Docker Build
      run: docker build -t jasminegraph .

    - name: Run Integration Tests
      run: |
        chmod +x test-docker.sh
        ./test-docker.sh

  k8s-integration-tests:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip k8s integration')}}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      - uses: jupyterhub/action-k3s-helm@v4
        with:
          docker-enabled: true

      - name: Grant permissions for default user
        run: kubectl apply -f ./k8s/rbac.yaml

      - name: Docker Build
        run: docker build -t jasminegraph .

      - name: K8S integration tests
        run: |
          chmod +x test-k8s.sh
          ./test-k8s.sh
