name: Style Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  style-check:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip style check')}}

    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends cpplint shfmt
          sudo wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -O /bin/hadolint && sudo chmod +x /bin/hadolint
          pip install pylint

      - name: hadolint check
        if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip hadolint Check')}}
        run: find . -type f -name '*Dockerfile*' -print0 | xargs -0 hadolint --ignore DL3008 --ignore DL3013 -t warning

      - name: shfmt check
        if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip shfmt Check')}}
        run: find . -type f -name '*.sh' -print0 | xargs -0 shfmt -d -s -i 4 -ci

      - name: cpplint check
        if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip cpplint Check')}}
        run: cpplint --linelength=120 --filter=-build,-runtime,-readability/todo,-whitespace/todo,-readability/casting,-readability/braces,-readability/fn_size,-legal/copyright --recursive .

      - name: pylint check
        if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip pylint Check')}}
        run: pylint -d C0103,E0401,R0801,R0902,R0913,R0914,R0915,W0603,W0621,W0718 --recursive=y .
