name: K8s release test
on:
  pull_request:
    branches: [master]

env:
  IMAGE: ishad1999/jasminegraph:v0.1.0-beta2
jobs:
  integration-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - uses: jupyterhub/action-k3s-helm@v4
        with:
          docker-enabled: true

      - name: See nodes
        run: kubectl get nodes -o wide

      - name: Pull image
        run: docker pull ${IMAGE}

      - name: K8S integration tests
        run: |
          sed -i "s#image: .*#image: ${IMAGE}#" k8s/master-deployment.yaml
          chmod +x test-k8s.sh
          ./test-k8s.sh

  integration-test-containerd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - uses: jupyterhub/action-k3s-helm@v4

      - name: See nodes
        run: kubectl get nodes -o wide

      - name: Pull image
        run: docker pull ${IMAGE}

      - name: K8S integration tests
        run: |
          sed -i "s#image: .*#image: ${IMAGE}#" k8s/master-deployment.yaml
          chmod +x test-k8s.sh
          ./test-k8s.sh